/* TU CONTENIDO — cambia este archivo; no hace falta editar el diseño.
 * Guarda tus archivos en media/ y usa rutas como "media/retrato-01.jpg".
 * cover: la foto o still que se ve en la portada y en All Works.
 * coverPosition: encuadre de la portada, por ejemplo "50% 30%".
 * category: "photography", "film" o "ads".
 * media: todas las imágenes y vídeos de la ficha, en orden.
 * Vídeo: { type: "video", src: "media/pelicula.mp4", poster: "media/still.jpg" }
 * Imagen: { type: "image", src: "media/foto.jpg", alt: "Descripción de la foto" }
 * Añade o quita proyectos copiando o eliminando un bloque completo.
 */
window.PORTFOLIO = {
  email: "ian@silentemedia.site", // Correo de trabajo.
  instagram: "https://www.instagram.com/ikn.ozz/", // URL completa de tu perfil.
  vimeo: "", // URL completa de tu perfil (opcional).
  projects: [
    {"id": "01", "title": "Secuencia final (Short film)", "category": "film", "year": "2025", "cover": "media/secuencia-final.jpeg", "description": "A psychological horror short film about a meta-mental persecution. I directed an adapted script written by someone else and also served as Director of Photography, colorist, and editor.", "media": [{"type": "youtube", "videoId": "7OwPkIUNjuA", "shareId": "hbaiY63BXI2pEvLg"}]},
    {"id": "02", "title": "SONAR - RiuzForzaXFitness", "category": "film", "year": "2026", "cover": "media/FitnessxRiusforza-sonar.jpg", "coverPosition": "50% 50%", "description": "Camera operator, colorist, and assistant editor for the live film shown during Fitness and Riusforza's Sónar performance.", "media": [{"type": "youtube", "videoId": "rn0o_8MqyXo", "shareId": "HWzPHM-auLxn2Vcy"}, {"type": "image", "src": "media/FitnessxRiusforza-sonar.jpg", "alt": "SONAR - RiuzForzaXFitness"}]},
    {"id": "03", "title": "Virtu (Revista) Film", "category": "film", "year": "2026", "cover": "media/Virtu Film.jpeg", "coverPosition": "50% 50%", "description": "A literary film for Virtu Magazine: a personal adaptation of a poem, created for publication in the magazine.", "media": [{"type": "youtube", "videoId": "KBN-Jc2SIZY", "shareId": "Vox2k8HWLnD-nno1"}, {"type": "image", "src": "media/Virtu Film.jpeg", "alt": "Virtu (Revista) Film"}, {"type": "image", "src": "media/virtu/2.jpeg", "alt": "Virtu (Revista) Film — still 2"}, {"type": "image", "src": "media/virtu/3.jpeg", "alt": "Virtu (Revista) Film — still 3"}, {"type": "image", "src": "media/virtu/4.jpeg", "alt": "Virtu (Revista) Film — still 4"}]},
    {"id": "04", "title": "Akrilla IzaTKM Nusaar 3000 Show", "category": "film", "year": "2026", "cover": "media/Akrilla IzaTKM Nusaar 3000 Show_1.10.1.jpg", "coverPosition": "50% 50%", "description": "Bts fragment from Akrilla's show on Sala Apolo Barcelona. Hosting the live visuals and camera aftemovies suport.", "media": [{"type": "video", "src": "https://silentmedia.site/portfolio%20Ian/Akrila%20Show.mov", "poster": "media/Akrilla IzaTKM Nusaar 3000 Show_1.10.1.jpg", "alt": "Akrilla IzaTKM Nusaar 3000 Show"}, {"type": "image", "src": "media/Akrilla IzaTKM Nusaar 3000 Show_1.10.1.jpg", "alt": "Akrilla IzaTKM Nusaar 3000 Show"}, {"type": "image", "src": "media/akrilla/still-02.jpeg", "alt": "Akrilla show — behind the scenes"}, {"type": "image", "src": "media/akrilla/still-03.jpeg", "alt": "Akrilla show — stage and live visuals"}]},
    {"id": "05", "title": "Self Defense Ad Spot", "category": "ads", "year": "2026", "cover": "media/vx1000.png", "coverPosition": "50% 50%", "description": "An art advertisement for an artifact by Codec, a 3D artist. I served as Director of Photography and assistant camera, and assisted with color. Edited by Adah García del Arco.", "media": [{"type": "youtube", "videoId": "0KDqoiyCINA", "shareId": "N7YeI0eI0hlJWo08"}, {"type": "image", "src": "media/vx1000.png", "alt": "Self Defense Ad Spot"}]},
    {"id": "06", "title": "Illojuan - Giovanillo's Pizza", "category": "ads", "year": "2026", "cover": "media/illojuan-066.jpg", "coverPosition": "50% 50%", "description": "A social media commercial for the launch of Giovanillo's Pizza by Spanish streamer IlloJuan. This is an unreleased version edited by me. I shot most of it alongside Codec, with photography by Álvaro Sin.", "media": [{"type": "youtube", "videoId": "z965sp3qnMA", "shareId": "f3C617d1inLpgMyd"}, {"type": "image", "src": "media/illojuan-066.jpg", "alt": "Illojuan - Giovanillo's Pizza"}, {"type": "image", "src": "media/illojuan/still-02.jpeg", "alt": "Illojuan — pizza table"}, {"type": "image", "src": "media/illojuan/still-03.jpeg", "alt": "Illojuan — pizza delivery"}, {"type": "image", "src": "media/illojuan/still-04.jpeg", "alt": "Illojuan — refrigerator shot"}, {"type": "image", "src": "media/illojuan/still-05.jpeg", "alt": "Illojuan — pizza box exterior"}, {"type": "image", "src": "media/illojuan/still-06.jpeg", "alt": "Illojuan — pizza campaign collage"}]},
    {"id": "07", "title": "ik-multimedia", "category": "ads", "year": "2026", "cover": "media/ik-multimedia.jpg", "coverPosition": "50% 50%", "description": "An advertising spot for IK Multimedia's TONEX ONE Plus, produced, directed, shot, and edited by me.", "media": [{"type": "youtube", "videoId": "aMBxUyYj3PM", "shareId": "k9FQ30ekUUUvmAkf"}, {"type": "image", "src": "media/ik-multimedia.jpg", "alt": "ik-multimedia"}, {"type": "image", "src": "media/ik-multimedia/still-02.png", "alt": "IK Multimedia — TONEX pedal"}, {"type": "image", "src": "media/ik-multimedia/still-03.png", "alt": "IK Multimedia — TONEX detail"}, {"type": "image", "src": "media/ik-multimedia/still-04.png", "alt": "IK Multimedia — musician at night"}, {"type": "image", "src": "media/ik-multimedia/still-05.png", "alt": "IK Multimedia — night portrait"}, {"type": "image", "src": "media/ik-multimedia/still-06.png", "alt": "IK Multimedia — studio scene"}, {"type": "image", "src": "media/ik-multimedia/still-07.png", "alt": "IK Multimedia — fisheye portrait"}, {"type": "image", "src": "media/ik-multimedia/still-08.png", "alt": "IK Multimedia — production credits"}]},
    {"id": "08", "title": "Festival B 2026", "category": "photography", "year": "2026", "cover": "media/Festival B 2026 - Rusowsky.jpg", "coverPosition": "50% 50%", "description": [{"text": "upcoming photos from Festival B (Barcelona) with "}, {"text": "Rusowsky", "bold": true}, {"text": ", "}, {"text": "Tristan", "bold": true}, {"text": " and "}, {"text": "La Rebe", "bold": true}, {"text": "."}], "media": [{"type": "image", "src": "media/Festival B 2026 - Rusowsky.jpg", "alt": "Festival B 2026 — Rusowsky"}]}
  ]
};
